INSERT INTO `bms`.`bms_movie` (`name`, `description`, `ratings`, `language`, `photo`, `genere`) VALUES 
('The Wolf of Wall Street', 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.', '8.2', 'English', 'https://ik.imagekit.io/qjolgcwzsel/wolfs_of_wallstreet_YbGw9jJ-xlI.jpg?updatedAt=1632766858588', 'Biopic, Drama'),
('The Theory of Everything', 'A look at the relationship between the famous physicist Stephen Hawking and his wife.', '7.7', 'English', 'https://ik.imagekit.io/qjolgcwzsel/theoryofeverything_oTBjwvIJZLG.jpg?updatedAt=1632766857694', 'Biopic, Drama'),
('The Big Short', 'In 2006-2007 a group of investors bet against the US mortgage market. In their research, they discover how flawed and corrupt the market is.', '7.8', 'English', 'https://ik.imagekit.io/qjolgcwzsel/the_big_short_tWQ6GcAwDtc.jpg?updatedAt=1632766856796', 'Drama'),
('The Social Network', 'As Harvard student Mark Zuckerberg creates the social networking site that would become known as Facebook, he is sued by the twins who claimed he stole their idea, and by the co-founder who was later squeezed out of the business.', '7.7', 'English', 'https://ik.imagekit.io/qjolgcwzsel/social_networks_71E0Um5nNOa.jpg?updatedAt=1632766855952', 'Drama'),
('October Sky', "The true story of Homer Hickam, a coal miner's son who was inspired by the first Sputnik launch to take up rocketry against his father's wishes.", '7.8', 'English', 'https://ik.imagekit.io/qjolgcwzsel/octobersky_-IE1KA829Pkm.jpg?updatedAt=1632766855134', 'Drama'),
('Steve Jobs', "Steve Jobs takes us behind the scenes of the digital revolution, to paint a portrait of the man at its epicenter. The story unfolds backstage at three iconic product launches, ending in 1998 with the unveiling of the iMac.", '7.2', 'English', 'https://ik.imagekit.io/qjolgcwzsel/jobs_tJ7Vv8K23zf.jpg?updatedAt=1632766854311', 'Drama'),
('J. Edgar', "J. Edgar Hoover, powerful head of the F.B.I. for nearly fifty years, looks back on his professional and personal life.", '6.5', 'English', 'https://ik.imagekit.io/qjolgcwzsel/j_edger_4Bz1kOYkkJd.jpg?updatedAt=1632766853469', 'Drama'),
('Homeless to Harvard', "Based on a true story. Liz Murray is a young girl who is taken care of by her loving, but drug-addicted parents. Liz becomes homeless at 15 and after a tragedy comes upon her, she begins her work to finish high school.", '7.2', 'English', 'https://ik.imagekit.io/qjolgcwzsel/home_less_harward_N1D8iOhhjhP.jpg?updatedAt=1632766852663', 'Drama'),
('Catch Me If You Can', "Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.", '8.1', 'English', 'https://ik.imagekit.io/qjolgcwzsel/catch_me_can_nP6JJjGZ4_l.jpg?updatedAt=1632766851801', 'Drama'),
('The Pursuit of Happyness', "A struggling salesman takes custody of his son as he's poised to begin a life-changing professional career.", '8.0', 'English', 'https://ik.imagekit.io/qjolgcwzsel/20872_4dUveGdFbN8.jpg?updatedAt=1632766851171', 'Drama');